name: chat_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.3.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  get_it: ^7.6.0
  go_router: ^9.0.3
  grouped_list: ^5.1.2
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
